trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build Stage
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
        npm test
      displayName: 'npm install, build, and test'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Pipeline'
      displayName: 'Publish Artifact'

# Deploy to Development Stage
- stage: Deploy_Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying to Development
            displayName: 'Deploy to Development'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(Build.BuildId)'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)'
            displayName: 'Download Build Artifact'
          - script: |
              # Add your deployment scripts here
              echo "Deploying to Development environment"
            displayName: 'Deploy Application'

# Deploy to Staging Stage
- stage: Deploy_Staging
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'Staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying to Staging
            displayName: 'Deploy to Staging'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(Build.BuildId)'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)'
            displayName: 'Download Build Artifact'
          - script: |
              # Add your deployment scripts here
              echo "Deploying to Staging environment"
            displayName: 'Deploy Application'

# Deploy to Production Stage
- stage: Deploy_Prod
  dependsOn: Deploy_Staging
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying to Production
            displayName: 'Deploy to Production'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(Build.BuildId)'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)'
            displayName: 'Download Build Artifact'
          - script: |
              # Add your deployment scripts here
              echo "Deploying to Production environment"
            displayName: 'Deploy Application'
